name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.17.3'
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests
      run: sbt +clean +coverage +test +coverageReport 
    - name: Aggregate coverage report
      run: sbt coverageAggregate 
    - name: Upload test coverage report
      run: bash <(curl -s https://codecov.io/bash)
